Flight matches vc
DmitrySmolyakov/FlightMatcher pull request #6
Opened 2017-04-03 15:55 UTC by dashvlas

2017-04-03 19:04 UTC, pknd commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/View/FlightMatchCell.swift
> +    func formatUnixTime(date: Date) -> String {
Why do we need this in a Cell class? 🙂

2017-04-03 19:04 UTC, pkandrashkou requested changes

2017-04-03 19:04 UTC, pknd commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/View/FlightMatchCell.swift
> +        self.fromToLabel.text = request.from.country + " " + request.from.city + " - " + request.to.country + " " + request.to.city
Please use string interpolation for combining strings.

2017-04-03 19:04 UTC, pknd commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/View/FlightMatchCell.swift
> +    func configure(withItem item: Any) {
Please try to avoid using `Any`. This is strong typed language and its not preferred to pass something around as `Any`.

2017-04-03 19:04 UTC, pknd commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/Controller/FlightMatchesController.swift
> +    func dataSource() -> [Request]? {
This is not a good idea to make dataSource a function. Every time you call for dataSource it's gonna call `getRequest()` and do parsing logic. You should definitely store it in a variable.

2017-04-03 19:04 UTC, pknd commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/Controller/FlightMatchesController.swift
> +        if let requests = dataSource()?.count {
This could be simplified like this
```swift
return dataSource()?.count ?? 0
```
Check out `??` and `?` operators 🙂

2017-04-03 20:02 UTC, DmitrySmolyakov commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/View/FlightMatchCell.swift
> +        self.fromToLabel.text = request.from.country + " " + request.from.city + " - " + request.to.country + " " + request.to.city
Something like this would be better
```
"/(request.from.country) /(request.from.city) - /(request.to.country) /(request.to.city)"
```

2017-04-03 20:04 UTC, DmitrySmolyakov commented on FlightMatcher/FlightMatcher/Stories/FlightMatch/View/FlightMatchCell.swift
> +    func formatUnixTime(date: Date) -> String {
Make this like extension for Date class, please

2017-04-04 11:24 UTC, pkandrashkou approved these changes

2017-04-04 11:24 UTC, merged